name: Build and deploy Simplechat
on:
  #push:
  #  branches:
  #    - Development
  workflow_dispatch:
    inputs:
      env:
        description: Environment
        required: true
        default: Nonprod
        type: choice
        options:
          - Nonprod
          - Prod
      tag:
        description: Tag
        required: true
        default: v0.212.091
        type: string

jobs:
  deploy:
      runs-on: ubuntu-latest
      environment:
        name: ${{ inputs.env }}
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      permissions:
        id-token: write #This is required for requesting the JWT
        contents: read #This is required for actions/checkout
  
      steps:
        - name: Download artifact github
          run: |
            curl -L -o release.zip https://github.com/microsoft/simplechat/archive/refs/tags/${{ inputs.tag }}.zip

  
        - name: Unzip artifact for deployment
          run: unzip release.zip && mv simplechat* simplechat
        
        - name: Set .env file
          env:
            MY_ENV: ${{ secrets.env }}
          shell: bash
          run: |
            ls -alh
            echo "$MY_ENV" >> simplechat/application/single_app/.env

  
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_336B3E5966FE46478F13B2BF15B403C5 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2614B88F070C47A6B88D88DDCC159F6F }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9D886361747A4226A8DF56937BFDBE5F }}
            environment: Production
  
        - name: 'Deploy to Azure Web App'
          uses: azure/webapps-deploy@v3
          id: deploy-to-webapp
          with:
            app-name: ${{ vars.APPNAME }}
            package: aimplechat/application/single_app/
            #slot-name: 'Production'
